# Generated by Django 5.2.9 on 2025-12-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Περιφέρεια')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
            ],
            options={
                'verbose_name': 'Περιφέρεια',
                'verbose_name_plural': 'Περιφέρειες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Π.χ. ΙΟΠ', max_length=20, unique=True, verbose_name='Κωδικός Ομίλου')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Ομίλου')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός Όμιλος')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='organizations.region', verbose_name='Περιφέρεια')),
            ],
            options={
                'verbose_name': 'Όμιλος',
                'verbose_name_plural': 'Όμιλοι',
                'ordering': ['code'],
            },
        ),
    ]
