# Generated by Django 5.2.9 on 2025-12-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_number', models.CharField(help_text='Από Excel: στήλη AM', max_length=30, unique=True, verbose_name='Αριθμός Μητρώου (Ιππου)')),
                ('name', models.CharField(max_length=120, verbose_name='Ίππος (Όνομα)')),
                ('passport_number', models.CharField(blank=True, max_length=60, verbose_name='Διαβατήριο')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
            ],
            options={
                'verbose_name': 'Ίππος',
                'verbose_name_plural': 'Ίπποι',
                'ordering': ['registry_number'],
            },
        ),
    ]
