# Generated by Django 5.2.9 on 2025-12-28 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('registry', '0003_alter_athlete_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['last_name', 'first_name', 'eoi_registry_number'], 'verbose_name': 'Αθλητής', 'verbose_name_plural': 'Αθλητές'},
        ),
        migrations.AlterModelOptions(
            name='athletemedicalcertificate',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Ιατρική Βεβαίωση Αθλητή', 'verbose_name_plural': 'Ιατρικές Βεβαιώσεις Αθλητών'},
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='address_number',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='address_postcode',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='registry_number',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.RemoveField(
            model_name='athletedocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='doctor_phone',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='doctor_specialty',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='eoi_registry_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Αριθμός Μητρώου ΕΟΙ'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='id_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='ΑΔΤ / Διαβατήριο'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='document_type',
            field=models.CharField(choices=[('OTHER', 'Λοιπό'), ('DOCUMENT', 'Έγγραφο'), ('MEDICAL', 'Ιατρική Βεβαίωση')], default='OTHER', max_length=20, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AddField(
            model_name='athletemedicalcertificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Έκδοσης'),
        ),
        migrations.AddField(
            model_name='athletemedicalcertificate',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='athletemedicalcertificate',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ισχύει μέχρι'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='amka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΜΚΑ'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Γέννησης'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='organizations.club', verbose_name='Όμιλος'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Επώνυμο'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Υπηκοότητα'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='file',
            field=models.FileField(upload_to='athlete_documents/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='file',
            field=models.FileField(upload_to='athlete_medicals/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='registry_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Μητρώου Ίππου (ΑΜ)'),
        ),
    ]
