# Generated by Django 5.2.9 on 2025-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_athlete_athlete_license_date_athlete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Αθλητή'),
        ),
    ]
