# Generated by Django 5.2.9 on 2025-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_athlete_athlete_license_date_horsedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Άδειας Αθλητή'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='document_type',
            field=models.CharField(choices=[('OTHER', 'Λοιπό'), ('PASSPORT', 'Διαβατήριο'), ('MEDICAL', 'Ιατρικό'), ('DOCUMENT', 'Έγγραφο')], default='OTHER', max_length=20, verbose_name='Τύπος Εγγράφου'),
        ),
    ]
