# Generated by Django 5.2.9 on 2025-12-22 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_number', models.CharField(help_text='Συμπληρώνεται μόνο από Administrator.', max_length=30, unique=True, verbose_name='Αριθμός Μητρώου ΕΟΙ')),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=120, verbose_name='Επώνυμο')),
                ('father_name', models.CharField(blank=True, max_length=120, verbose_name='Όνομα Πατέρα')),
                ('mother_name', models.CharField(blank=True, max_length=120, verbose_name='Όνομα Μητέρας')),
                ('birth_date', models.DateField(verbose_name='Ημερομηνία Γέννησης')),
                ('birth_place', models.CharField(blank=True, max_length=120, verbose_name='Τόπος Γέννησης')),
                ('nationality', models.CharField(blank=True, max_length=80, verbose_name='Υπηκοότητα')),
                ('id_document', models.CharField(blank=True, max_length=50, verbose_name='ΑΔΤ / Διαβατήριο')),
                ('amka', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Το ΑΜΚΑ πρέπει να έχει 11 ψηφία.')], verbose_name='ΑΜΚΑ')),
                ('address_street', models.CharField(max_length=120, verbose_name='Διεύθυνση - Οδός')),
                ('address_number', models.CharField(max_length=20, verbose_name='Διεύθυνση - Αριθμός')),
                ('address_city', models.CharField(max_length=80, verbose_name='Διεύθυνση - Πόλη')),
                ('address_postcode', models.CharField(max_length=12, verbose_name='Διεύθυνση - ΤΚ')),
                ('phone1', models.CharField(max_length=30, verbose_name='Τηλέφωνο 1')),
                ('email1', models.EmailField(max_length=254, verbose_name='Email 1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο 2')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Εγγραφής')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='organizations.club', verbose_name='Όμιλος')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Αθλητής',
                'verbose_name_plural': 'Αθλητές',
                'ordering': ['registry_number'],
            },
        ),
        migrations.CreateModel(
            name='AthleteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('APPLICATION', 'Αίτηση Εγγραφής'), ('CONSENT', 'Συγκατάθεση'), ('OTHER', 'Λοιπό')], max_length=30, verbose_name='Τύπος Εγγράφου')),
                ('file', models.FileField(upload_to='athletes/documents/', verbose_name='Αρχείο')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Ανέβασματος')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.athlete', verbose_name='Αθλητής')),
            ],
            options={
                'verbose_name': 'Έγγραφο Αθλητή',
                'verbose_name_plural': 'Έγγραφα Αθλητών',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteMedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='Ιατρός - Ονοματεπώνυμο')),
                ('doctor_specialty', models.CharField(blank=True, max_length=120, verbose_name='Ιατρός - Ειδικότητα')),
                ('doctor_phone', models.CharField(blank=True, max_length=30, verbose_name='Ιατρός - Τηλέφωνο')),
                ('exam_date', models.DateField(verbose_name='Ημερομηνία Εξέτασης')),
                ('expiry_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('file', models.FileField(upload_to='athletes/medical/', verbose_name='Αρχείο Κάρτας Υγείας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='registry.athlete', verbose_name='Αθλητής')),
            ],
            options={
                'verbose_name': 'Ιατρική Βεβαίωση Αθλητή',
                'verbose_name_plural': 'Ιατρικές Βεβαιώσεις Αθλητών',
                'ordering': ['-expiry_date', '-created_at'],
            },
        ),
    ]
