# Generated by Django 5.2.9 on 2025-12-29 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_athlete_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='father_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='first_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='mother_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Δημιουργήθηκε'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='document_type',
            field=models.CharField(choices=[('OTHER', 'Λοιπό'), ('DOCUMENT', 'Έγγραφο')], default='OTHER', max_length=20, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε'),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε'),
        ),
    ]
