# Generated by Django 5.2.9 on 2025-12-30 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('registry', '0010_alter_athlete_options_alter_athletedocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['eoi_registry_number'], 'verbose_name': 'Αθλητής', 'verbose_name_plural': 'Αθλητές'},
        ),
        migrations.AlterModelOptions(
            name='athletedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Έγγραφο Αθλητή', 'verbose_name_plural': 'Έγγραφα Αθλητών'},
        ),
        migrations.AlterModelOptions(
            name='horse',
            options={'ordering': ['registry_number'], 'verbose_name': 'Ίππος', 'verbose_name_plural': 'Ίπποι'},
        ),
        migrations.AlterModelOptions(
            name='horsedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Έγγραφο Ίππου', 'verbose_name_plural': 'Έγγραφα Ίππων'},
        ),
        migrations.AddField(
            model_name='athlete',
            name='amka',
            field=models.CharField(blank=True, max_length=20, verbose_name='ΑΜΚΑ'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='athlete_license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Άδειας Αθλητή'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='organizations.club', verbose_name='Όμιλος'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Δημιουργήθηκε'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Όνομα Πατέρα'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='father_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='first_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='id_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='ΑΔΤ / Διαβατήριο'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργός'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Όνομα Μητέρας'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='mother_name_uc',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Υπηκοότητα'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε'),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έκδοσης'),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ισχύει μέχρι'),
        ),
        migrations.AddField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης'),
        ),
        migrations.AddField(
            model_name='horse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργός'),
        ),
        migrations.AddField(
            model_name='horse',
            name='passport',
            field=models.CharField(blank=True, max_length=120, verbose_name='Διαβατήριο'),
        ),
        migrations.AddField(
            model_name='horsedocument',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έκδοσης'),
        ),
        migrations.AddField(
            model_name='horsedocument',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ισχύει μέχρι'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='eoi_registry_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Μητρώου ΕΟΙ'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Επώνυμο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='document_type',
            field=models.CharField(choices=[('registration_application', 'Αίτηση εγγραφής'), ('transfer_application', 'Αίτηση μεταγραφής'), ('medical_certificate', 'Ιατρική βεβαίωση'), ('certificate', 'Πιστοποιητικό'), ('other', 'Άλλο έγγραφο')], default='other', max_length=40, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='athlete_documents/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Καταχωρήθηκε'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ίππος'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='registry_number',
            field=models.CharField(max_length=60, unique=True, verbose_name='Αριθμός Μητρώου Ίππου (ΑΜ)'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Διαβατήριο'), ('medical', 'Ιατρικό'), ('certificate', 'Πιστοποιητικό'), ('other', 'Λοιπό')], default='other', max_length=40, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='horse_documents/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Καταχωρήθηκε'),
        ),
        migrations.CreateModel(
            name='AthleteMedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έκδοσης')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ισχύει μέχρι')),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_certificates/%Y/%m/', verbose_name='Αρχείο')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Καταχωρήθηκε')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='registry.athlete', verbose_name='Αθλητής')),
            ],
            options={
                'verbose_name': 'Ιατρική Βεβαίωση Αθλητή',
                'verbose_name_plural': 'Ιατρικές Βεβαιώσεις Αθλητών',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
