# Generated by Django 5.2.9 on 2025-12-30 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('registry', '0011_alter_athlete_options_alter_athletedocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['last_name', 'first_name', 'eoi_registry_number'], 'verbose_name': 'Αθλητής', 'verbose_name_plural': 'Αθλητές'},
        ),
        migrations.RemoveField(
            model_name='athletedocument',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='athletedocument',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='athletemedicalcertificate',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='horsedocument',
            name='issued_at',
        ),
        migrations.AddField(
            model_name='athlete',
            name='birth_place',
            field=models.CharField(blank=True, max_length=120, verbose_name='Τόπος Γέννησης'),
        ),
        migrations.AddField(
            model_name='athletemedicalcertificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Έκδοσης'),
        ),
        migrations.AddField(
            model_name='horse',
            name='passport_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Διαβατήριο'),
        ),
        migrations.AddField(
            model_name='horsedocument',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Έκδοσης'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='amka',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΜΚΑ'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Γέννησης'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='organizations.club', verbose_name='Όμιλος'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Δημιουργήθηκε'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Αθλητή'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='eoi_registry_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Αριθμός Μητρώου ΕΟΙ'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='ΑΔΤ / Διαβατήριο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='document_type',
            field=models.CharField(choices=[('MEDICAL', 'Ιατρική Βεβαίωση'), ('REGISTRATION', 'Αίτηση Εγγραφής'), ('TRANSFER', 'Αίτηση Μεταγραφής'), ('CERTIFICATE', 'Πιστοποιητικό'), ('OTHER', 'Άλλο έγγραφο')], default='OTHER', max_length=30, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='file',
            field=models.FileField(upload_to='athlete_documents/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε'),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='file',
            field=models.FileField(upload_to='athlete_medicals/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νια Γέννησης'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ίππος'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='registry_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Μητρώου Ίππου (ΑΜ)'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Διαβατήριο'), ('MEDICAL', 'Ιατρικό'), ('CERTIFICATE', 'Πιστοποιητικό'), ('OTHER', 'Λοιπό')], default='OTHER', max_length=30, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='file',
            field=models.FileField(upload_to='horse_documents/%Y/%m/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε'),
        ),
    ]
