# Generated by Django 5.2.9 on 2025-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='address_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Διεύθυνση - Πόλη'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Διεύθυνση - Αριθμός'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=12, verbose_name='Διεύθυνση - ΤΚ'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='address_street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Διεύθυνση - Οδός'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο 1'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='registry_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Μητρώου ΕΟΙ'),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Εξέτασης'),
        ),
        migrations.AlterField(
            model_name='athletemedicalcertificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νια Γέννησης'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ίππος'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='passport_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Διαβατήριο'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='registry_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Αριθμός Μητρώου Ίππου (AM)'),
        ),
    ]
