# Generated by Django 5.2.9 on 2025-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_athlete_father_name_uc_athlete_first_name_uc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete_license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Άδειας Αθλητή'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Αθλητή'),
        ),
    ]
