# Generated by Django 5.2.9 on 2025-12-29 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_athlete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Άδειας Αθλητή'),
        ),
        migrations.CreateModel(
            name='HorseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Διαβατήριο'), ('MEDICAL', 'Ιατρικό'), ('OTHER', 'Λοιπό')], default='OTHER', max_length=20, verbose_name='Τύπος Εγγράφου')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Ημερ/νία Έκδοσης')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ισχύει μέχρι')),
                ('file', models.FileField(upload_to='horse_documents/%Y/%m/', verbose_name='Αρχείο')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Καταχωρήθηκε')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.horse', verbose_name='Ίππος')),
            ],
            options={
                'verbose_name': 'Έγγραφο Ίππου',
                'verbose_name_plural': 'Έγγραφα Ίππων',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
