# Generated by Django 5.2.9 on 2025-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_athlete_athlete_license_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={},
        ),
        migrations.AlterModelOptions(
            name='athletedocument',
            options={'verbose_name': 'Έγγραφο Αθλητή', 'verbose_name_plural': 'Έγγραφα Αθλητών'},
        ),
        migrations.AlterModelOptions(
            name='horse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='horsedocument',
            options={'verbose_name': 'Έγγραφο Ίππου', 'verbose_name_plural': 'Έγγραφα Ίππων'},
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='amka',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='athlete_license_date',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='club',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='email',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='father_name_uc',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='first_name_uc',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_name_uc',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='mother_name_uc',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='horsedocument',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='horsedocument',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='eoi_registry_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='document_type',
            field=models.CharField(choices=[('medical', 'Ιατρική Βεβαίωση'), ('registration', 'Αίτηση Εγγραφής'), ('transfer', 'Αίτηση Μεταγραφής'), ('certificate', 'Πιστοποιητικό'), ('other', 'Άλλο Έγγραφο')], max_length=20, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='file',
            field=models.FileField(upload_to='athlete_documents/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='athletedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='horse',
            name='registry_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Διαβατήριο'), ('medical', 'Ιατρικό Πιστοποιητικό'), ('certificate', 'Πιστοποιητικό'), ('other', 'Άλλο Έγγραφο')], max_length=20, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='file',
            field=models.FileField(upload_to='horse_documents/', verbose_name='Αρχείο'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='horsedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='AthleteMedicalCertificate',
        ),
    ]
